# Generated by Django 2.2.3 on 2019-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50)),
                ('count_N', models.IntegerField()),
                ('persons_count', models.IntegerField()),
                ('motorcycle_count', models.IntegerField()),
                ('bicycle_count', models.IntegerField()),
                ('car_count', models.IntegerField()),
                ('bus_count', models.IntegerField()),
                ('truct_count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
