# Generated by Django 2.2.3 on 2019-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='bicycle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='bus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='car_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='count_N',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='motorcycle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='persons_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='truct_count',
            field=models.IntegerField(default=0),
        ),
    ]
