# Generated by Django 2.2.3 on 2019-08-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_auto_20190807_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
    ]
